# Generated by Django 5.2.8 on 2025-12-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_aluno_email_alter_aluno_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='aluno_id',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='curso_id',
            new_name='curso',
        ),
    ]
