# Generated by Django 5.2.8 on 2025-12-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_rename_aluno_id_matricula_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.aluno'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'curso'), name='unique_aluno_curso', violation_error_message='Este aluno já está matriculado neste curso.'),
        ),
    ]
