# Generated by Django 5.2.8 on 2025-12-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_alter_matricula_aluno_matricula_unique_aluno_curso'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aluno',
            table='aluno',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='matricula',
        ),
    ]
